### ISSUE TITLE
Will this new model be open source like PixArt-alpha?

### ISSUE THREAD

**Issue by Datou** [PixArt-alpha/PixArt-sigma#1]
(●'◡'●)ﾉ

**Comment by nemonameless** [comment]
@xieenze  when will the codes datasets and weights be released? thx

**Comment by xieenze** [comment]
> @xieenze when will the codes datasets and weights be released? thx

We plan to release the code and pre-trained models in the next 2-3 weeks. But we may not release the dataset due to some complex reasons(e.g. company etc.)

**Comment by habanerogossip** [comment]
> > @xieenze when will the codes datasets and weights be released? thx
> 
> We plan to release the code and pre-trained models in the next 2-3 weeks. But we may not release the dataset due to some complex reasons(e.g. company etc.)

Nice. If you end up not releasing the dataset, maybe consider releasing some more details like which websites were used so that finetuners don't end up training from the same sources

**Comment by lawrence-cj** [comment]
Released. Will keep updating this repo for a long time. Thanks again for you guys support.
