### ISSUE TITLE
这个算法比playgorund v2.5强太多了

### ISSUE THREAD

**Issue by rwywenyi** [PixArt-alpha/PixArt-sigma#10]
Playground v2.5宣传出来的效果很强，使用了一下，还不如PixArt-alpha版本的效果，
要知道，PixArt-alpha训练数据要少的多得多

**Comment by lawrence-cj** [comment]
Released. Will keep updating this repo for a long time. Thanks again for you guys support.

**Comment by xiexiaoshinick** [comment]
强在那里？我测试了一下，生成图像在美学评分，提示词following和图像中文字生成方面与playgroundv2.5差距还很大。华为论文上也承认这一点，就硬吹么？
