### ISSUE TITLE
About VAE

### ISSUE THREAD

**Issue by berryxue** [PixArt-alpha/PixArt-sigma#106]
I want to fine-tune 1024 model, can I directly use VAE and text_encoder from https://huggingface.co/PixArt-alpha/PixArt-Sigma-XL-2-1024-MS/tree/main? Or must use these models from https://huggingface.co/PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers/tree/main?

**Comment by ReyJ94** [comment]
you may be get your answers faster if you ask about finetuning questions from pixart discord server

**Comment by lawrence-cj** [comment]
Yes. You can directly use them.
