### ISSUE TITLE
PixArt Sigma output image is only messy noise

### ISSUE THREAD

**Issue by VGF64** [PixArt-alpha/PixArt-sigma#109]
I did everything to set up correctly with this on ComfyUI but when I keep attempting to generate an image it gives me this every time.

![ComfyUI_00436_](https://github.com/PixArt-alpha/PixArt-sigma/assets/126835875/20528152-cf8c-4447-93f0-5f49f04f0293)

Any idea what went wrong here?

**Comment by chrish-slingshot** [comment]
Can you share your workflow?

**Comment by VGF64** [comment]
> Can you share your workflow?

Yes, here: 
![Screenshot (363)](https://github.com/PixArt-alpha/PixArt-sigma/assets/126835875/63651af7-2349-42e0-a0fd-76838e6d8665)

I wanna assume and believe it has something to do with the T5v1.1 Loader node. Not too entirely certain.

**Comment by chrish-slingshot** [comment]
[pixart_sigma_test_2.json](https://github.com/user-attachments/files/15722506/pixart_sigma_test_2.json)

Strange, I recreated it and it works ok on my machine. Can you try the attached workflow? If it still fails, I would lean toward it being a VAE problem - maybe try redownloading the Sigma VAE again.

**Comment by VGF64** [comment]
I downloaded and then redownloaded the VAE from this link via photographer's workflow of PixArt Sigma on CivitAI: https://huggingface.co/PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers/tree/main/vae

And then I downloaded this VAE as well: https://huggingface.co/PixArt-alpha/PixArt-Sigma-XL-2-1024-MS/tree/main/vae

All of which is still giving me the same messy noise.

![Screenshot (364)](https://github.com/PixArt-alpha/PixArt-sigma/assets/126835875/5a23c1c8-b659-441c-b5ff-24a9c49850c4)

**Comment by VGF64** [comment]
I resolved it! I had to follow this guide and it did the trick! https://civitai.com/articles/5355/installing-comfyui-for-use-with-pixart-sigma

I think it (might?) have something to do with me not having xformers, as I didn't have it installed in my Comfy venv.
