### ISSUE TITLE
Parallel Feature Extraction

### ISSUE THREAD

**Issue by alfredplpl** [PixArt-alpha/PixArt-sigma#115]
This is an amazing project.
Even I can create image generation from scratch.

However, the problem I'm currently facing is that feature extraction using the T5 encoder cannot be done in parallel.
To extract features from 1.2M images, parallel extraction is essential.
But with the current code, extraction can only be done with a single GPU.

How should I address this issue? Please advise.

**Comment by lawrence-cj** [comment]
We have `start_index` and `end_index` in the extracting script, which is used to run several commands at the same time in a .sh file. Same as the parallel you said.

https://github.com/PixArt-alpha/PixArt-sigma/blob/30c3297259da6544295168c14a67500f35397ab3/tools/extract_features.py#L307

**Comment by alfredplpl** [comment]
Thank you!
I do so.
