### ISSUE TITLE
Better installation tutorial/dependencies?

### ISSUE THREAD

**Issue by Darksoulmaster31** [PixArt-alpha/PixArt-sigma#17]
The models got released today, so I decided to try them out, but unfortunately, it just doesn't work for me.

No matter how many times I reinstall the (provided .yml) conda environment with multiple python and pytorch versions (settled on python 3.10.11 and pytorch 2.2.2+cu121 because that's what xformers was prebuilt for), it just would not work and it kept throwing errors like: (cannot import name 'CpuOffload' from 'accelerate.hooks'). Even tried to separately update diffusers, transformers and accelerate with pip but that made it worse.
The Demo will NOT launch.
_It's probably just my incompetence really, but I hope someone here can help._

If the future diffusers integration helps with the dependency hell then I can simply wait for it.
### Despite these issues, thank you all for your wonderful work. 🙏🙏🙏

(Windows 10 | Conda with multiple python/pytorch versions and pip packages tested | Geforce RTX 3090)

**Comment by Darksoulmaster31** [comment]
With some help from [Bigfield77](https://github.com/Bigfield77), I've got the workflow.
Make a conda environment with **Python 3.10.9**, install the requirements.txt with `pip`, then install Pytorch 2.2.2 (with cuda 12.1 support)

After this, **if you are on windows**, go to **line 21 of** `PixArt-sigma\diffusion\utils\logger.py` and change the location to somewhere else like this: `log_file = 'D:/Temp/log.out'`

After downloading the models using the `tools/download.py`, you need to put the `pixart_sigma_sdxlvae_T5_diffusers` folder into the `output\pretrained_models` folder.

Then replace the vae inside the `pixart_sigma_sdxlvae_T5_diffusers/vae` folder with this: [fp16 vae fix model link](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/main/diffusion_pytorch_model.safetensors)

**Comment by Goldenkoron** [comment]
> With some help from [Bigfield77](https://github.com/Bigfield77), I've got the workflow. Make a conda environment with **Python 3.10.9**, install the requirements.txt with `pip`, then install Pytorch 2.2.2 (with cuda 12.1 support)
> 
> After this, **if you are on windows**, go to **line 21 of** `PixArt-sigma\diffusion\utils\logger.py` and change the location to somewhere else like this: `log_file = 'D:/Temp/log.out'`
> 
> After downloading the models using the `tools/download.py`, you need to put the `pixart_sigma_sdxlvae_T5_diffusers` folder into the `output\pretrained_models` folder.
> 
> Then replace the vae inside the `pixart_sigma_sdxlvae_T5_diffusers/vae` folder with this: [fp16 vae fix model link](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/main/diffusion_pytorch_model.safetensors)

I have done all of this and still getting this error:

Inference with torch.float16
Warning: position embed interpolation: 2, base size: 64
kv compress config: {'sampling': None, 'scale_factor': 1, 'kv_compress_layer': []}
Generating sample from ckpt: output/pretrained_models/PixArt-Sigma-XL-2-512-MS.pth
Traceback (most recent call last):
  File "C:\Users\User\Desktop\SD\Pixart\PixArt-sigma\inference.py", line 180, in <module>
    del state_dict['state_dict']['pos_embed']
KeyError: 'pos_embed'

**Comment by Darksoulmaster31** [comment]
Thank you for the [commit](https://github.com/PixArt-alpha/PixArt-sigma/commit/592d4650ed5ad5f4efbc24376181cd519a9fa5b2), it's greatly appreciated. Issue solved for now, closing....
