### ISSUE TITLE
1024px checkpoint

### ISSUE THREAD

**Issue by saeedkhanehgir** [PixArt-alpha/PixArt-sigma#20]
Hi 
I am very surprised by this model. thanks for sharing this project. 

Do you have any plans to release  1024*1024 checkpoint?

**Comment by ApolloRay** [comment]
https://huggingface.co/PixArt-alpha/PixArt-Sigma/blob/main/PixArt-Sigma-XL-2-1024-MS.pth

**Comment by lawrence-cj** [comment]
Currently available
