### ISSUE TITLE
sigma vs alpha

### ISSUE THREAD

**Issue by liangwq** [PixArt-alpha/PixArt-sigma#21]
The images generated by this version seem not to adhere to instructions as well as the previous alpha version did, and the quality of the generated images also appears to be inferior to that of the previous version. Why is this the case? Wasn't this version of the model expanded in terms of parameters or trained with an extended dataset based on the previous version?

**Comment by liangwq** [comment]
https://loc.dingtalk.com/L1VzZXJzL3FpYW4tbHdxL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvMzQ2MzM3NDFfdjIvSW1hZ2VGaWxlcy8xNzEyNTgyNzgyNDM5X0FDNUJFNTc1LTI4NDktNEVFNy1CRDJDLUFBQjkyNDBBMUNhttps://loc.dingtalk.com/L1VzZXJzL3FpYW4tbHdxL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvMzQ2MzM3NDFfdjIvSW1hZ2VGaWxlcy8xNzEyNTg0ODE3NTcxXzAxMEVFNDg3LTQ3MjUtNDVBRi04MzhDLTU0MzM1QzMyMTQwMy5wbmc=?renderWidth=384&renderHeight=672&renderOrientation=1&isLocal=1CRS5wbmc=?renderWidth=1024&renderHeight=1536&renderOrientation=1&isLocal=1

**Comment by ApolloRay** [comment]
> https://loc.dingtalk.com/L1VzZXJzL3FpYW4tbHdxL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvMzQ2MzM3NDFfdjIvSW1hZ2VGaWxlcy8xNzEyNTgyNzgyNDM5X0FDNUJFNTc1LTI4NDktNEVFNy1CRDJDLUFBQjkyNDBBMUNhttps://loc.dingtalk.com/L1VzZXJzL3FpYW4tbHdxL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvMzQ2MzM3NDFfdjIvSW1hZ2VGaWxlcy8xNzEyNTg0ODE3NTcxXzAxMEVFNDg3LTQ3MjUtNDVBRi04MzhDLTU0MzM1QzMyMTQwMy5wbmc=?renderWidth=384&renderHeight=672&renderOrientation=1&isLocal=1CRS5wbmc=?renderWidth=1024&renderHeight=1536&renderOrientation=1&isLocal=1

Can't open this link.

**Comment by liangwq** [comment]
![AC5BE575-2849-4EE7-BD2C-AAB9240A1CBE](https://github.com/PixArt-alpha/PixArt-sigma/assets/9170648/42a12ddb-bb01-46c1-aec4-c0d61d213533)
![010EE487-4725-45AF-838C-54335C321403](https://github.com/PixArt-alpha/PixArt-sigma/assets/9170648/88ad65c1-316d-4d7b-8bbf-3a33d8a05ade)

**Comment by ApolloRay** [comment]
> ![AC5BE575-2849-4EE7-BD2C-AAB9240A1CBE](https://private-user-images.githubusercontent.com/9170648/320701436-42a12ddb-bb01-46c1-aec4-c0d61d213533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mjk5MDAsIm5iZiI6MTcxMjYyOTYwMCwicGF0aCI6Ii85MTcwNjQ4LzMyMDcwMTQzNi00MmExMmRkYi1iYjAxLTQ2YzEtYWVjNC1jMGQ2MWQyMTM1MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA4YjE1MWFkNDM5YjFlYjMwMGYwOWZkZjc3ZmUzM2Q2NDFhOTA4Zjc3OGQ3MDIzNmZiZTE3ZjgyNTYyZGZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xmBTOfGIJ210raJJ7bMp-WoRWItG4F3DsMtppGC4c4k) ![010EE487-4725-45AF-838C-54335C321403](https://private-user-images.githubusercontent.com/9170648/320701449-88ad65c1-316d-4d7b-8bbf-3a33d8a05ade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mjk5MDAsIm5iZiI6MTcxMjYyOTYwMCwicGF0aCI6Ii85MTcwNjQ4LzMyMDcwMTQ0OS04OGFkNjVjMS0zMTZkLTRkN2ItOGJiZi0zYTMzZDhhMDVhZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg1Y2M0Y2I0OWM1N2UyYjY3NTkyYmYwZDQ4ZmY5MmYyMGYyYzg4ZmQxMzE4ZDZhN2Y1NjdiN2FiM2FiYWQ2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LZA0eHbnv9QTHX4OKEkfE3DPEniNWeV0k6xvvaauB2c)

I think you have to use a benchmark to eval these two models.

**Comment by liangwq** [comment]
> > ![AC5BE575-2849-4EE7-BD2C-AAB9240A1CBE](https://private-user-images.githubusercontent.com/9170648/320701436-42a12ddb-bb01-46c1-aec4-c0d61d213533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mjk5MDAsIm5iZiI6MTcxMjYyOTYwMCwicGF0aCI6Ii85MTcwNjQ4LzMyMDcwMTQzNi00MmExMmRkYi1iYjAxLTQ2YzEtYWVjNC1jMGQ2MWQyMTM1MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA4YjE1MWFkNDM5YjFlYjMwMGYwOWZkZjc3ZmUzM2Q2NDFhOTA4Zjc3OGQ3MDIzNmZiZTE3ZjgyNTYyZGZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xmBTOfGIJ210raJJ7bMp-WoRWItG4F3DsMtppGC4c4k) ![010EE487-4725-45AF-838C-54335C321403](https://private-user-images.githubusercontent.com/9170648/320701449-88ad65c1-316d-4d7b-8bbf-3a33d8a05ade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Mjk5MDAsIm5iZiI6MTcxMjYyOTYwMCwicGF0aCI6Ii85MTcwNjQ4LzMyMDcwMTQ0OS04OGFkNjVjMS0zMTZkLTRkN2ItOGJiZi0zYTMzZDhhMDVhZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg1Y2M0Y2I0OWM1N2UyYjY3NTkyYmYwZDQ4ZmY5MmYyMGYyYzg4ZmQxMzE4ZDZhN2Y1NjdiN2FiM2FiYWQ2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LZA0eHbnv9QTHX4OKEkfE3DPEniNWeV0k6xvvaauB2c)
> 
> I think you have to use a benchmark to eval these two models.

This is because I used the same prompt for generating effects. The two models should be able to maintain consistency in following the same instructions; the new model has enhanced certain capabilities. Otherwise, the model lacks continuity.

**Comment by ApolloRay** [comment]
> This is because I used the same prompt for generating effects. The two models should be able to maintain consistency in following the same instructions; the new model has enhanced certain capabilities. Otherwise, the model lacks continuity.

![截屏2024-04-09 10 50 55](https://github.com/PixArt-alpha/PixArt-sigma/assets/36093263/8c41583d-bbdc-4b27-84c4-ff0f6c7cf434)
I can't understand the consistency. In the paper, same prompt can't get same result.

**Comment by ApolloRay** [comment]
> The images generated by this version seem not to adhere to instructions as well as the previous alpha version did, and the quality of the generated images also appears to be inferior to that of the previous version. Why is this the case? Wasn't this version of the model expanded in terms of parameters or trained with an extended dataset based on the previous version?

I think you have to read this paper at first. It's different from the embedding length, captionner method , etc.

**Comment by liangwq** [comment]
> > This is because I used the same prompt for generating effects. The two models should be able to maintain consistency in following the same instructions; the new model has enhanced certain capabilities. Otherwise, the model lacks continuity.
> 
> ![截屏2024-04-09 10 50 55](https://private-user-images.githubusercontent.com/36093263/320706303-8c41583d-bbdc-4b27-84c4-ff0f6c7cf434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM1NDMsIm5iZiI6MTcxMjYzMzI0MywicGF0aCI6Ii8zNjA5MzI2My8zMjA3MDYzMDMtOGM0MTU4M2QtYmJkYy00YjI3LTg0YzQtZmYwZjZjN2NmNDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzMjcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDBhMzJhZTc3YjkyOWJlMDMzMmUzNGY5ZTBhYzVlOWViZDY3Yjc2MmFjNjgwMzY4MDUxNmQ1YjU1ZDE2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m6YlrJZkj1KXof-a6ysZItmC-LenQoswvN_CNpyob6M) I can't understand the consistency. In the paper, same prompt can't get same result.

Yes, you see the difference between the effects given in the paper and the actual test results. I think the effects mentioned in the paper are acceptable, but how big is the difference under the same prompt in actual tests?

**Comment by ApolloRay** [comment]
> > This is because I used the same prompt for generating effects. The two models should be able to maintain consistency in following the same instructions; the new model has enhanced certain capabilities. Otherwise, the model lacks continuity.
> 
> It would be better to use the same initial noise for the two models. Besides, the sigma model is finetuned on the alpha model with the changed dataset. It would be the main reason for the two model have differeces.

Today, the DMD model wil be released ?

**Comment by lawrence-cj** [comment]
1024 ckpt today. DMD then.

**Comment by ApolloRay** [comment]
> 1024 ckpt today. DMD then.

thx.

**Comment by lawrence-cj** [comment]
During our test, we use the diffusers version(coming soon) which may be slightly different from the inference code in this repo. But we choosed the same noise as input here for testing: https://github.com/PixArt-alpha/PixArt-sigma/blob/592d4650ed5ad5f4efbc24376181cd519a9fa5b2/scripts/interface.py#L115

Besides, if you are familiar with the diffusion model' s training, the results may just be different as the training going on between different epoches. Or do you know any method that can help to make the model performs similar content but higher quality during training? I would like to give it a try.

**Comment by lawrence-cj** [comment]
Would you pls DM me in the discord community so that we can have a further discussion? I'm curious about the idea.

**Comment by liangwq** [comment]
> Would you pls DM me in the discord community so that we can have a further discussion? I'm curious about the idea.

Can you give me your Discord ID? How can I contact you?

**Comment by lawrence-cj** [comment]
https://discord.gg/rde6eaE5Ta
