### ISSUE TITLE
Colab demo for PIXART-Σ

### ISSUE THREAD

**Issue by sohowj** [PixArt-alpha/PixArt-sigma#22]
On the project homepage of PIXART-Σ (https://pixart-alpha.github.io/PixArt-sigma-project/), a Colab Demo link is provided, but the code inside seems to be prepared for PixArt-α:

`!pip install diffusers transformers sentencepiece accelerate`
`import torch`
`from diffusers import PixArtAlphaPipeline`
`pipe = PixArtAlphaPipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", torch_dtype=torch.float16)`
`pipe = pipe.to('cuda')`

There are a few questions here:
1. For PIXART-Σ, should I still use the PixArtAlphaPipeline object?
2. If I want to use the pretrained model of PIXART-Σ, what should be changed to "PixArt-alpha/PixArt-XL-2-1024-MS" in the above code? I tried "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS" and "PixArt-sigma/PixArt-Sigma-XL-2-1024-MS" but it didn't work

**Comment by lawrence-cj** [comment]
The diffusers pipeline for pixart-Sigma is developing. Plz stay tuned!
