### ISSUE TITLE
accelerator.wait_for_everyone()时机有问题，导致多机多卡训练显卡利用率上不去

### ISSUE THREAD

**Issue by conansherry** [PixArt-alpha/PixArt-sigma#23]
可以参考
[https://github.com/kohya-ss/sd-scripts/blob/71e2c91330a9d866ec05cdd10584bbb962896a99/sdxl_train.py#L651](https://github.com/kohya-ss/sd-scripts/blob/71e2c91330a9d866ec05cdd10584bbb962896a99/sdxl_train.py#L651)

**Comment by lawrence-cj** [comment]
Thx so much. Changed. Would you plz help to check if the changes are correct: https://github.com/PixArt-alpha/PixArt-sigma/commit/dc27d4f8e9e64f1770957fe3cad0c45c1e627a4f
