### ISSUE TITLE
Inquiry About Hardware Requirements and Training Details for PIXART-Σ

### ISSUE THREAD

**Issue by sohowj** [PixArt-alpha/PixArt-sigma#24]
I am planning to train the model using the training code provided in https://github.com/PixArt-alpha/PixArt-sigma and am currently gathering information to understand the necessary hardware and data requirements. I would appreciate if you could provide some insights based on your experiences with PIXART-Σ. Specifically, I have the following questions:

1. What hardware configurations were used for training the model, e.g., how many Nvidia A100/H100 GPUs? (or other types of GPUs)
2. Could you specify the size of the dataset used during training?
3. How long did the training process take?

Any details you provide will be incredibly helpful as I am trying to estimate the resources and time needed for my own training setup.

Thank you in advance for your assistance!

**Comment by lawrence-cj** [comment]
1.All of our experiments are done using maximum 32 V100 GPUs.
2-3. As we talked about in both [PixArt-α: 15M dataset](https://arxiv.org/abs/2310.00426) and [PixArt-Σ:30M dataset](https://arxiv.org/abs/2403.04692). For details, please refer to the Paper

<img width="878" alt="image" src="https://github.com/PixArt-alpha/PixArt-sigma/assets/55283454/b17904be-f00d-4340-a042-a4143ac8e4d4">

<img width="733" alt="image" src="https://github.com/PixArt-alpha/PixArt-sigma/assets/55283454/596e86e9-37df-4275-b094-6074616dd336">

**Comment by kingkong135** [comment]
what is mean "32x32" in Batch size, it is use battch size 32 in 32 computer ?
