### ISSUE TITLE
DMD load problems

### ISSUE THREAD

**Issue by chuck-ma** [PixArt-alpha/PixArt-sigma#26]
First ,it seems that the model should be loaded as safetensors.Because no safetensors files in https://huggingface.co/PixArt-alpha/PixArt-Alpha-DMD-XL-2-512x512/tree/main.

pipe = PixArtAlphaPipeline.from_pretrained(
        model_path,
        subfolder="transformer",
        torch_dtype=weight_dtype,
        use_safetensors=False,
    )
    
    
Besides, it seems that I can't load the PixArtAlphaPipeline somehow cause some config file missing.

OSError: Error no file named config.json found in directory /root/.cache/huggingface/hub/models--PixArt-alpha--PixArt-Alpha-DMD-XL-2-512x512/snapshots/57df7bb32daad69bc1d6c825a275935113802169.

**Comment by EYcab** [comment]
The same error caught here.

**Comment by lawrence-cj** [comment]
OK. Let's fix it.

**Comment by lawrence-cj** [comment]
Fixed. Let's have a try. https://github.com/PixArt-alpha/PixArt-sigma/commit/2ba2f6efd4b5c6e922ecda04102ceba1430003ec
