### ISSUE TITLE
No such file or directory: 'output/pretrained_models/null_embed_diffusers_300token.pth'

### ISSUE THREAD

**Issue by xiaoxiaodadada** [PixArt-alpha/PixArt-sigma#28]
When running the following training program:
python -m torch.distributed.launch --nproc_per_node=1 --master_port=12345 train_scripts/train.py configs/pixart_sigma_config/PixArt_sigma_xl2_img256_internal.py --load-from output/pretrained_models/PixArt-Sigma-XL-2-256x256.pth --work-dir output/test --debug
![微信图片_20240411202603](https://github.com/PixArt-alpha/PixArt-sigma/assets/125524021/615cb0f8-0973-48a7-83be-c29e96867ef2)
Are there any missing files? I am missing something. Thank you very much if you can help me.

**Comment by lawrence-cj** [comment]
U need to make sure your training passes this line. 
https://github.com/PixArt-alpha/PixArt-sigma/blob/318c5a5dd82c96fda587bbeaeeac74525a95fe3b/train_scripts/train.py#L390

**Comment by xiaoxiaodadada** [comment]
get it, thank you~

**Comment by lawrence-cj** [comment]
What is causing the problem?

**Comment by xiaoxiaodadada** [comment]
I just ran 512 first, and it ran through and saved there. Then I ran 256 and it was fine.

**Comment by FeiSong123** [comment]
Does it mean that I need to train a 512 model first to obtain 'output/pretrained_models/null_embed_diffusers_300token.pth', and then use it for training the 256 model?
