### ISSUE TITLE
Unexpected results with `diffusers`

### ISSUE THREAD

**Issue by chenxwh** [PixArt-alpha/PixArt-sigma#29]
Hi, thanks for the great work and integration to `diffusers`!

However when trying exactly the snippets provided [here](https://github.com/PixArt-alpha/PixArt-sigma?tab=readme-ov-file#2-integration-in-diffusers), I got strange results below. Any idea what might have gone wrong?

![catcus](https://github.com/PixArt-alpha/PixArt-sigma/assets/70536672/4833aba9-352f-4ce6-ae00-9ec4323260e6)

Thank you!

**Comment by Beinsezii** [comment]
The official diffusers converted weights are broken. Use something like `niklasku/PixArt-Sigma-XL-2-1024-MS` instead.

**Comment by lawrence-cj** [comment]
Did you upload the `diffusers` with `pip install git+https://github.com/huggingface/diffusers`?

**Comment by Beinsezii** [comment]
`"PixArt-alpha/PixArt-Sigma-XL-2-1024-MS"` as the transformer
![00243](https://github.com/PixArt-alpha/PixArt-sigma/assets/39478211/8da8d941-f35a-40cd-aa61-46d7915c6920)

`"niklasku/PixArt-Sigma-XL-2-1024-MS"` as the transformer, identical parameters otherwise
![00242](https://github.com/PixArt-alpha/PixArt-sigma/assets/39478211/4c2c42cd-3b70-4bf6-801c-4db07b979c11)

I just pulled `diffusers/main` 5 minutes ago to make these images.

**Comment by lawrence-cj** [comment]
Cool. Let me check it.

**Comment by lawrence-cj** [comment]
It's strange. If you load the file in `"niklasku/PixArt-Sigma-XL-2-1024-MS`
```python
from safetensors.torch import load_file
d = load_file('/home/xieenze/chenjunsong/code/diffusion/Pixart/output/pretrained_models/PixArt-Sigma-XL-2-hf_others/diffusion_pytorch_model.safetensors')
```
There are plenty of layers are just all zeros?
![image](https://github.com/PixArt-alpha/PixArt-sigma/assets/55283454/eed6ecfd-68a0-4605-9c37-1b8405e7ff3e)

**Comment by Beinsezii** [comment]
Padding?

**Comment by lawrence-cj** [comment]
I re-upload a new safetensor file upto the hugginface: https://huggingface.co/PixArt-alpha/PixArt-Sigma-XL-2-1024-MS/tree/main. You can give it a try.

**Comment by Beinsezii** [comment]
Yes that one works. @chenxwh Should try again.

 What ended up being the cause?

It might be worth investigating the x512 diffusers as well. My colleague had said he was having issues with them too. Maybe needs the same fix?

**Comment by lawrence-cj** [comment]
Some layers in the previous ckpt are broken. I have re-uploaded all the 256px, 512px and 1024px ckpt. Let me know if the 512 ckpt is also working well now.
