### ISSUE TITLE
坐等中……

### ISSUE THREAD

**Issue by jesuswa** [PixArt-alpha/PixArt-sigma#3]

**Comment by xieenze** [comment]
Thank you for your attention! We will consider open source part of the code and pre-training weights in the near future (within 2-3 weeks).

**Comment by CrazyBoyM** [comment]
不像阿里那样挂羊头！支持！！

**Comment by Richard0403** [comment]
> 不像阿里那样挂羊头！支持！！

这不是一样的么？ 有啥区别？

**Comment by CrazyBoyM** [comment]
人家写了即将开源的日期


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月14日(周四) 下午3:03
收件人: ***@***.***&gt;;
抄送: &quot;Ke ***@***.******@***.***&gt;;
主题: Re: [PixArt-alpha/PixArt-sigma] 坐等中&hellip;&hellip; (Issue #3)




  
不像阿里那样挂羊头！支持！！
  
这不是一样的么？ 有啥区别？
 
&mdash;

**Comment by einsflash** [comment]
期待

**Comment by lawrence-cj** [comment]
Released. Will keep updating this repo for a long time. Thanks again for you guys support.
