### ISSUE TITLE
how do you pre-procecss 512-size images?

### ISSUE THREAD

**Issue by EternalEvan** [PixArt-alpha/PixArt-sigma#30]
Dear authors,
     Your work is so impressive and thanks for your codes. I am confused about how you pre-process the 512-size images since you use the SDXL-VAE that defaults for 1024-size images. Looking forward to your early reply!

**Comment by lawrence-cj** [comment]
SDXL-VAE can be used to 512 images too

**Comment by EternalEvan** [comment]
True. Thanks for your help!
