### ISSUE TITLE
Question about KV compression in diffusers

### ISSUE THREAD

**Issue by lijing1996** [PixArt-alpha/PixArt-sigma#35]
I saw diffusers_patches.py. However, I don't know where is the KV compression and how can I use this py file? Could you help me? Thanks.

**Comment by lawrence-cj** [comment]
`KV compression` ckpt is not released yet.
The `diffusers_patches.py` is used in diffusers: https://github.com/PixArt-alpha/PixArt-sigma?tab=readme-ov-file#2-integration-in-diffusers
