### ISSUE TITLE
Would you like to provide more details of dmd training?

### ISSUE THREAD

**Issue by RyanHuangNLP** [PixArt-alpha/PixArt-sigma#38]
Thank you very much for your excellent open-source work. Can you provide more details about the DMD training? 
1.how much training data was used and how much GPU time was required?
2.why not train dmd on sigma, is it 1024 model hard to distill?

**Comment by lawrence-cj** [comment]
1. Use the same 640K data as the original paper with 8 V100 GPUs. The model is trained for more than 2 days.
2. Sigma and Alpha don't have much difference. No 80G GPUs for 1024 distillation.
