### ISSUE TITLE
How much graphics memory is required to run the above test? 

### ISSUE THREAD

**Issue by shams2023** [PixArt-alpha/PixArt-sigma#43]
![image](https://github.com/PixArt-alpha/PixArt-sigma/assets/141383792/4563313e-9803-4333-b8dd-b2f0dc86b63f)

How much graphics memory is required to run the above test? Mine is 12GB, but it shows OOM. Can I deploy it locally on 12GB graphics memory?
Looking forward to your answer!
Thank you!

**Comment by ApolloRay** [comment]
> ![image](https://private-user-images.githubusercontent.com/141383792/323051598-4563313e-9803-4333-b8dd-b2f0dc86b63f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzUwNTcsIm5iZiI6MTcxMzMzNDc1NywicGF0aCI6Ii8xNDEzODM3OTIvMzIzMDUxNTk4LTQ1NjMzMTNlLTk4MDMtNDMzMy1iOGRkLWIyZjBkYzg2YjYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNjE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjJkYmUwNGVkNDFkMGM3MTViNWM0NTE5NzgwMGQ2N2JmYmU1MmM4MTg5MmMxMTA5YzQyZGY2MmI4ZTAzY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MngmBNrOL617Op0r5LNiHidAKhpigcUUmMuitxIFWTA)
> 
> How much graphics memory is required to run the above test? Mine is 12GB, but it shows OOM. Can I deploy it locally on 12GB graphics memory? Looking forward to your answer! Thank you!

https://github.com/PixArt-alpha/PixArt-sigma/issues/19 , follow this issue.

**Comment by lawrence-cj** [comment]
18GB minimum with https://github.com/PixArt-alpha/PixArt-sigma#3-pixart-demo.
8GB with https://github.com/PixArt-alpha/PixArt-sigma/blob/master/asset/docs/pixart.md

**Comment by shams2023** [comment]
> 至少 18GB https://github.com/PixArt-alpha/PixArt-sigma#3-pixart-demo。 8GB，https://github.com/PixArt-alpha/PixArt-sigma/blob/master/asset/docs/pixart.md

thanks！

**Comment by shams2023** [comment]
> 18GB minimum with https://github.com/PixArt-alpha/PixArt-sigma#3-pixart-demo. 8GB with https://github.com/PixArt-alpha/PixArt-sigma/blob/master/asset/docs/pixart.md

![image](https://github.com/PixArt-alpha/PixArt-sigma/assets/141383792/3c053544-09cd-45a8-8a33-b5ff12eae3f3)
How much graphics memory is needed for the above interface.py?

**Comment by lawrence-cj** [comment]
Around 24GB

**Comment by shams2023** [comment]
> Around 24GB

thank you !
