### ISSUE TITLE
高分辨率的图就是直接 resize 放大的？

### ISSUE THREAD

**Issue by wodsoe** [PixArt-alpha/PixArt-sigma#48]
参数一样，seed一样的话，1024x1024跟2048x2048的图，是一样的？高分辨率的图就是直接 resize 放大的吗？
![QQ截图20240418110225](https://github.com/PixArt-alpha/PixArt-sigma/assets/40934627/bf2e914f-5a54-4990-b417-c786b50ff18f)
![QQ截图20240418110330](https://github.com/PixArt-alpha/PixArt-sigma/assets/40934627/ca7ecbda-d1e9-4c80-8b63-39e14b5aa6ff)

**Comment by lawrence-cj** [comment]
The current demo is using 1024px checkpoint. Will release 2K checkpoint later. Plz stay tuned.
Refer to: https://github.com/PixArt-alpha/PixArt-sigma#to-do-list
