### ISSUE TITLE
There is a gap with stable diffusion

### ISSUE THREAD

**Issue by conansherry** [PixArt-alpha/PixArt-sigma#53]
After fine-tuning it with my own data set, I tested it. In the realistic style, t2i gen images, although the clarity has been improved somewhat, the beauty of the opponents and faces feels far behind than sdxl, let alone sd3. Because the model 0.6B itself has limited capabilities?

**Comment by lawrence-cj** [comment]
The main reason maybe the training dataset. Our goal is not to generate real images, but refined images. If you want to generate more realistic ones, collect your dataset and finetune the model would be fine. I don't think the model size would be a problem to handle realistic style.

**Comment by kelisiya** [comment]
> The main reason maybe the training dataset. Our goal is not to generate real images, but refined images. If you want to generate more realistic ones, collect your dataset and finetune the model would be fine. I don't think the model size would be a problem to handle realistic style.

Is there any relevant research that shows that larger Pixart models will improve the authenticity and logic of production? When I input some prompts with spatial logic relationships, such as: there is a dog on a box, a cat on the left, and a horse on the right, there will be problems, and it always feels like an oil painting style.

**Comment by lawrence-cj** [comment]
If you have seen the limitation stated in our papar, you will know the spatial, counting is not our best. We tried to enlarge the model and the counting ability will be improved. As for the spatial logic, you need to design specific prompt in the dataset to enhance the ability
<img width="256" alt="image" src="https://github.com/PixArt-alpha/PixArt-sigma/assets/55283454/518a7b9c-b22a-446c-beeb-cd68c578e4ec">

**Comment by kelisiya** [comment]
> If you have seen the limitation stated in our papar, you will know the spatial, counting is not our best. We tried to enlarge the model and the counting ability will be improved. As for the spatial logic, you need to design specific prompt in the dataset to enhance the ability <img alt="image" width="256" src="https://private-user-images.githubusercontent.com/55283454/323850876-518a7b9c-b22a-446c-beeb-cd68c578e4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDgyNzUsIm5iZiI6MTcxMzUwNzk3NSwicGF0aCI6Ii81NTI4MzQ1NC8zMjM4NTA4NzYtNTE4YTdiOWMtYjIyYS00NDZjLWJlZWItY2Q2OGM1NzhlNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MjYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGNhNWM3NjliYjk1YjE1NDBjNGVlOWRmNzg1YmIxOWUyZDNlMTRiYWU1ZDljNTBmMTMwMTI5MmI0NWI0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17Fe49KnaiZc5C8YJsNmDie2dduQCsDymYNYWyvpQZg">

Thank you for your efficient answer, I think in finetune my data set lost the relevant logic and was too concerned with the longer prompts and therefore lost the situation discussed in the article, I will reconstruct my data again to debug

**Comment by toilaluan** [comment]
@kelisiya @lawrence-cj
hi, thanks for your nice work
I just want to ask about your recent training progress @kelisiya
