### ISSUE TITLE
VAE for the DMD model

### ISSUE THREAD

**Issue by EternalEvan** [PixArt-alpha/PixArt-sigma#56]
Hello, I noticed that the pre-trained pipeline for DMD model has a different VAE compared with the PixART-Sigma-MS-1024 which uses SDXL's VAE.  And I try to use the SDXL's VAE for DMD model but it gives bad results. So what's the VAE for the DMD model? Have you tuned the VAE yourself?

**Comment by lawrence-cj** [comment]
It's just the PixArt-Alpha's VAE, also for the SDV1, V2 and so on.

**Comment by Feynman1999** [comment]
> Hello, I noticed that the pre-trained pipeline for DMD model has a different VAE compared with the PixART-Sigma-MS-1024 which uses SDXL's VAE. And I try to use the SDXL's VAE for DMD model but it gives bad results. So what's the VAE for the DMD model? Have you tuned the VAE yourself?

Has your result improved using the combination of sdxl vae and pixart sigma？
