### ISSUE TITLE
Some problems with graio loading training weights

### ISSUE THREAD

**Issue by kelisiya** [PixArt-alpha/PixArt-sigma#59]
When I trained for several rounds of epochs and wanted to use Gradio for testing, I found that epoch_1 and epoch_2 were fine, but epoch_3 "WARNING - Unexpected keys: ['blocks.14.attn.sr.weight',", and then the inference crashed, and I want to know what happened

**Comment by lawrence-cj** [comment]
train script, logs, test scipts, config file. 
Without these I can't help you.

**Comment by kelisiya** [comment]
> train script, logs, test scipts, config file. Without these I can't help you.

I found the problem, sorry, when I wrongly loaded the weight training the saved results and the configuration file did not match
