### ISSUE TITLE
Question about Samplers

### ISSUE THREAD

**Issue by YanzuoLu** [PixArt-alpha/PixArt-sigma#65]
Hi, thanks for your great work!
I'm curious why the sampling of pixart models must use DPMSolver?
I notice a significant quality drop when use DDIM even the steps are increased to 50.
To best of my knowledge, the convergence should be the same?
Below shows the diff between DPMSolver-20-Step and DDIM-50-Step.
![1 girl, by Sorayama-dpmsolver20](https://github.com/PixArt-alpha/PixArt-sigma/assets/43648617/7f3ea43a-c48c-41dc-a837-7a89a5e1c83f)
![1 girl, by Sorayama-ddim50](https://github.com/PixArt-alpha/PixArt-sigma/assets/43648617/f3dadbaf-f35b-40c6-b5f8-945118702820)

**Comment by lawrence-cj** [comment]
It's the advancement of DPMSolver against DDIM. Not just for PixArt I think?
You could try DDIMStep=100. Then they may be closer.
BTW, for ODE solver, you can also try SASolver which is also our default setting.

**Comment by YanzuoLu** [comment]
Okay, it's quite strange since increasing the inference steps to 100 does not bring much difference from the 50-Step one.
While the advancement of DPMSolver against DDIM in UNet-based SD models is almost invisible.
Anyway thanks for your suggestions!
