### ISSUE TITLE
About token limations?

### ISSUE THREAD

**Issue by rainsoulsrx** [PixArt-alpha/PixArt-sigma#7]
Hi, I notice that in pixart alpha paper, you mentioned 120 tokens are used. But in this page "[https://pixart-alpha.github.io/](https://pixart-alpha.github.io/) ", some examples token number is exceed 120. Just trunct to 120? 
examples:
---------------------------------------------
"The parametric hotel lobby is a sleek and modern space with plenty of natural light. The lobby is spacious and open with a variety of seating options. The front desk is a sleek white counter with a parametric design. The walls are a light blue color with parametric patterns. The floor is a light wood color with a parametric design. There are plenty of plants and flowers throughout the space. The overall effect is a calm and relaxing space. occlusion, moody, sunset, concept art, octane rendering, 8k, highly detailed, concept art, highly detailed, beautiful scenery, cinematic, beautiful light, hyperreal, octane render, hdr, long exposure, 8K, realistic, fog, moody, fire and explosions, smoke, 50mm f2.8"

**Comment by xieenze** [comment]
Hi, in Pixar-sigma paper, the token length limitation is extended to 300.

**Comment by lawrence-cj** [comment]
Released. Will keep updating this repo for a long time. Thanks again for you guys support.

**Comment by wrapss** [comment]
The message "The following part of your input was truncated because CLIP can only handle sequences up to 120 tokens" is still present when using the snippet to run the latest model with diffusers. Is this normal?

**Comment by lawrence-cj** [comment]
Plz pass the value 300 to this line when using diffusers pipeline. https://github.com/PixArt-alpha/PixArt-sigma/blob/dd087141864e30ec44f12cb7448dd654be065e88/app/app_pixart_sigma.py#L249

**Comment by wrapss** [comment]
> Plz pass the value 300 to this line when using diffusers pipeline.
> 
> https://github.com/PixArt-alpha/PixArt-sigma/blob/dd087141864e30ec44f12cb7448dd654be065e88/app/app_pixart_sigma.py#L249

very quick response! thank you
