### ISSUE TITLE
Fine-tuning script based on diffusers

### ISSUE THREAD

**Issue by youngwanLEE** [PixArt-alpha/PixArt-sigma#72]
Hi,
I appreciate your excellent work and sharing the code.

I wonder if you will release fine-tuning (training) code with diffusers as you already released the [training script](https://github.com/PixArt-alpha/PixArt-alpha/blob/master/train_scripts/train_diffusers.py) based on diffusers in the pixart-alpha repo? 

It would be very helpful if you share the fine-tuning code based on diffusers.

**Comment by lawrence-cj** [comment]
Will be in the future. The training with fp16 + `diffusers` is unstable. We encourage our users to train with original repo.

**Comment by youngwanLEE** [comment]
@lawrence-cj Thanks for your quick reply :)

**Comment by lawrence-cj** [comment]
BTW, the training script will be similar to alpha one. You can have a quick apply.
