### ISSUE TITLE
In some scenarios, there are poor performance issues in 2K checkpoint.

### ISSUE THREAD

**Issue by kelisiya** [PixArt-alpha/PixArt-sigma#77]
. When I tested with 2k weights, I noticed a lot of graininess. I would like to know if this is caused by insufficient training. If I want to fine-tune for this scenario, do you have any suggestions?
[image](https://www.imagehub.cc/image/Interior-Design%2C-Indoor-space%2C-Livingroom-interior-design%2CContemporary%2CPeter-Marino%2CArtwork%2CSectiona.b1oMok)

**Comment by lawrence-cj** [comment]
Correct. We only use 8A100, 200K images(4K steps not finishing one epoch during training.) You can further improve it with more training data and time.
