### ISSUE TITLE
where can I find config.json?

### ISSUE THREAD

**Issue by 1sheep1** [PixArt-alpha/PixArt-sigma#79]
![image](https://github.com/PixArt-alpha/PixArt-sigma/assets/128389620/0a2736fe-d8c2-4bd8-87b4-756b005e366b)
I want to train a lora, but there is a wrong.

**Comment by lawrence-cj** [comment]
Does the folder of your `PixArt-Sigma-XL-2-512-MS` have the file `transformer/config.json`?

**Comment by 1sheep1** [comment]
Thank you.
