### ISSUE TITLE
What are the extra 4 channels from the denoiser?

### ISSUE THREAD

**Issue by samedii** [PixArt-alpha/PixArt-sigma#81]
Been trying to figure it out from this
https://github.com/PixArt-alpha/PixArt-sigma/blob/master/train_scripts/train.py#L122

Learned variance maybe?

It looks like they are not used in your finetuning script but I might be wrong.

**Comment by lawrence-cj** [comment]
Which line? Your link seems not link to the right place?

**Comment by samedii** [comment]
Sorry I mean the 4 extra channels that the transformer outputs (it outputs 8). Only the first 4 channels are actually used in both finetuning and inference as far I can tell.

**Comment by samedii** [comment]
If you want LOC then
- https://github.com/PixArt-alpha/PixArt-sigma/blob/master/train_scripts/train_pixart_lora_hf.py#L862
- https://github.com/PixArt-alpha/PixArt-sigma/blob/master/diffusion/model/gaussian_diffusion.py#L789

Is it a leftover from experimenting with other `ModelVarType` previously and the final model was not trained with this?
https://github.com/PixArt-alpha/PixArt-sigma/blob/master/diffusion/model/gaussian_diffusion.py#L798

**Comment by lawrence-cj** [comment]
Oh yes, this part we just align with the original DiT implementation without changing.
