### ISSUE TITLE
Only three days.

### ISSUE THREAD

**Issue by ApolloRay** [PixArt-alpha/PixArt-sigma#9]

**Comment by rwywenyi** [comment]
hahahahhahahha

**Comment by ApolloRay** [comment]
I love huawei rather than alibaba.

**Comment by lawrence-cj** [comment]
Released. Will keep updating this repo for a long time. Thanks again for you guys support.

**Comment by ApolloRay** [comment]
> Released. Will keep updating this repo for a long time. Thanks again for you guys support.

Love you so much.
