### ISSUE TITLE
how to train sigma lora?

### ISSUE THREAD

**Issue by YLongJin** [PixArt-alpha/PixArt-sigma#90]
I modify the lora code and import the sigma model success，but the valuation save image is not chance！

**Comment by lawrence-cj** [comment]
How about the inference output? Any changing?

**Comment by YLongJin** [comment]
@lawrence-cj 
thanks your  response.
when I modify the sigma pipeline the lora work， but I can not train 1girl like SD, The inference result not much change

**Comment by lawrence-cj** [comment]
> when I modify the sigma pipeline the lora work， but I can not train 1girl like SD

Sry, but I don't understand very clearly. Would you like to explain more?

**Comment by YLongJin** [comment]
@lawrence-cj like this lora https://civitai.com/models/104759/easy-age-slider-for-1girl,when I train sigma lora, the 1girl not change.
